// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm3yLaY1z6VwM1it-uH-5B0GsVs3bgKFo',
    appId: '1:157609132575:web:acbc877a70763f710b4b2a',
    messagingSenderId: '157609132575',
    projectId: 'movie-trailer-af228',
    authDomain: 'movie-trailer-af228.firebaseapp.com',
    storageBucket: 'movie-trailer-af228.appspot.com',
    measurementId: 'G-0KXGF9KWPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbWHKcoODWEL07jZNeoHMPEexvDIGUgc',
    appId: '1:157609132575:android:963f5a0dafadddc40b4b2a',
    messagingSenderId: '157609132575',
    projectId: 'movie-trailer-af228',
    storageBucket: 'movie-trailer-af228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOq9t5Df873ZWrZ-6b1NClNPmZqbY9Js',
    appId: '1:157609132575:ios:d17780f45aaddbd20b4b2a',
    messagingSenderId: '157609132575',
    projectId: 'movie-trailer-af228',
    storageBucket: 'movie-trailer-af228.appspot.com',
    iosClientId: '157609132575-0kpglh9eodhrggpah2c6o73bvctqkpih.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATOq9t5Df873ZWrZ-6b1NClNPmZqbY9Js',
    appId: '1:157609132575:ios:92dbc3196ee171900b4b2a',
    messagingSenderId: '157609132575',
    projectId: 'movie-trailer-af228',
    storageBucket: 'movie-trailer-af228.appspot.com',
    iosClientId: '157609132575-taunce1j3duimt7lsm8o6kl31rr1b249.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie.RunnerTests',
  );
}
